location = "East US"
resource_group_name = "retry-pattern-resources-esteban"
app_service_plan_name = "retry-pattern-appserviceplan-esteban"
address_app_service_name = "retry-pattern-address-service-esteban"
order_app_service_name = "retry-pattern-order-service-esteban"
