location = "East US"
resource_group_name = "retry-pattern-resources"
acr_name = "retrypatternacr"
app_service_plan_name = "retry-pattern-appserviceplan"
address_app_service_name = "retry-pattern-address-service"
order_app_service_name = "retry-pattern-order-service"
